config/routes.rb
Rails.application.routes.draw do

  resources :profiles, only: [:edit, :update, :destroy, :create]

  get '/admin' => 'admin#index'
  get '/dashboard' => 'dashboard#index'
  get '/help' => 'help#index'

  devise_for :users, controllers: {confirmations: 'local_devise/confirmations',
                                   registrations: 'local_devise/registrations',
                                   unlocks: 'local_devise/unlocks',
                                   passwords: 'local_devise/passwords'}

  root 'dashboard#index'

  get 'devise_usage_report', to: 'devise_usage_log#devise_usage_report'
  get 'close_devise_usage_report', to: 'devise_usage_log#close_devise_usage_report'

end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  skip_authorization_check only: [:index]

  def index
  end
end

app/helpers/dashboard_helper.rb
module DashboardHelper

  require 'bundler'
  def bundled_gems
    Bundler.load.specs
  end

  def all_gems
    cnt = 0
    others = "<table class='table'><tr><td>"
    bundled_gems.sort { |gem_a, gem_b|gem_a.name <=> gem_b.name }.each do |spec|
      cnt += 1
      others += "#{spec.name} #{spec.version}<br />"
      others += '</td><td>' if (cnt % 18) == 0
    end
    others +  '</td></tr></table>'
  end

  def display_devise_version
    gem = bundled_gems.find { |str| str.name =~ /devise/ }
    "#{gem.name} #{gem.version}<br />"
  end

  def display_bootstrap_version
    gem = bundled_gems.find { |str| str.name =~ /bootstrap/ }
    "#{gem.name} #{gem.version}<br />"
  end

  def display_cancan_version
    gem = bundled_gems.find { |str| str.name =~ /cancan/ }
    "#{gem.name} #{gem.version}<br />"
  end

end

app/views/dashboard/partials/_listgems.html.haml
.row
  .col-md-2
    Rails #{Rails.version}
    %br/
    Ruby #{RUBY_VERSION}
    %br/
  .col-md-3
    = display_bootstrap_version.html_safe
  .col-md-2
    = display_devise_version.html_safe
    = display_cancan_version.html_safe
  .col-md-3
    %button.btn.btn-sm.btn-default{data: {target: '#list_gems', toggle: 'collapse'}, type: 'button'} +/- List All Gems
.row.collapse#list_gems
  %br/
  = all_gems.html_safe

app/views/dashboard/partials/_login_form.html.haml
= form_for(:user, as: 'user', url: session_path(:user), html: {role: 'form', class: 'form-horizontal'}) do |f|
  .modal-body
    -# = format_user_error_messages(:user)
    .form-group
      %label.col-md-3.control-label.devise.normal{for: 'inputUsername1'}= t('label.username')
      .col-md-9
        = f.text_field :username, class: 'form-control', id: 'inputUsername1', placeholder: t('label.username').downcase
    .form-group
      %label.col-md-3.control-label.devise.normal{for: 'inputPassword1'}= t('label.password')
      .col-md-9
        = f.password_field :password, class: 'form-control', id: 'inputPassword1', placeholder: t('label.password').downcase
    .form-group
      .col-md-offset-3.col-md-9
        .checkbox
          %label.devise.small-text
            = f.check_box :remember_me
            = t('label.remember_me')
    .form-group
      .col-md-offset-3.col-md-9
        .row
          .col-md-3
            = f.submit t('button.login'), class: 'btn btn-success'
          .col-md-offset-2.col-md-6.small-text
            = link_to 'Forgot&nbsp;password?'.html_safe, new_password_path(:user)
            = link_to 'Other&nbsp;login&nbsp;help'.html_safe, help_path
    .form-group
      %hr.green/
      = link_to t('button.register'), new_registration_path(:user), class: 'btn btn-block btn-primary'