config/routes.rb
Rails.application.routes.draw do

  resources :profiles, only: [:edit, :update, :destroy, :create]

  get '/admin' => 'admin#index'
  get '/dashboard' => 'dashboard#index'
  get '/help' => 'help#index'

  devise_for :users, controllers: {confirmations: 'local_devise/confirmations',
                                   registrations: 'local_devise/registrations',
                                   unlocks: 'local_devise/unlocks',
                                   passwords: 'local_devise/passwords'}

  root 'dashboard#index'

  get 'devise_usage_report', to: 'devise_usage_log#devise_usage_report'
  get 'close_devise_usage_report', to: 'devise_usage_log#close_devise_usage_report'

end

app/views/admin/partials/_add_user.html.haml
%br/
%hr.green/
= form_for User.new, url: profiles_path, html: {class: 'form-inline', role: 'form', id: 'admin_new_user', data: {remote: true, spinner: '#admin_new_user_spinner'}} do |f|
  .container
    .row
      .col-md-8
        #add_user_errors
        %label Add new user:
        .form-group
          %label.sr-only{for: 'username'}= t('label.username')
          = f.text_field :username, class: 'form-control', placeholder: t('label.username').downcase, autocomplete: 'off', id: 'username'
        .form-group
          %label.sr-only{for: 'email'}= t('label.email')
          = f.email_field :email, class: 'form-control', placeholder: t('label.email_example').downcase, autocomplete: 'off', id: 'email'
        = f.submit t('button.save'), class: 'btn btn-success btn-sml'
        = spinner_tag('admin_new_user_spinner').html_safe
%br/

app/views/admin/partials/_users.html.haml
%table.table.table-hover.table-condensed
  %thead
    %tr
      %th #
      %th= t('label.username')
      - if current_user.role?('admin')
        %th= t('label.email')
        %th= t('label.ip')
        %th= t('label.role')
      %th= t('label.last_login')
      %th= t('label.login_count')
      %th
  %tbody
    - @users.each do |user|
      %tr
        %td= user.id
        %td= display_user_name(user).html_safe
        - if current_user.role?('admin')
          %td= display_email(user).html_safe
          %td= display_last_ip(user)
          %td= user.role
        %td= display_last_login(user)
        %td= user.sign_in_count if user.sign_in_count > 0
        %td
          - if current_user.role?('admin') && (user.username.downcase != current_user.username.downcase)
            = link_to t('button.edit'), edit_profile_path(id: user.id),
                      title: t('tooltip.edit_user'), rel: :tooltip,
                      data: {toggle: 'modal', target: 'edit_user_modal'},
                      remote: true, class: 'btn btn-success btn-xs'
          - else
            ''

= render 'admin/partials/add_user'

.modal#edit_user_modal{aria: {labelledby: 'myModalLabel', hidden: true}, role: 'dialog', tabindex: '-1'}