config/routes.rb
Rails.application.routes.draw do

  resources :profiles, only: [:edit, :update, :destroy, :create]

  get '/admin' => 'admin#index'
  get '/dashboard' => 'dashboard#index'
  get '/help' => 'help#index'

  devise_for :users, controllers: {confirmations: 'local_devise/confirmations',
                                   registrations: 'local_devise/registrations',
                                   unlocks: 'local_devise/unlocks',
                                   passwords: 'local_devise/passwords'}

  root 'dashboard#index'

  get 'devise_usage_report', to: 'devise_usage_log#devise_usage_report'
  get 'close_devise_usage_report', to: 'devise_usage_log#close_devise_usage_report'

end

app/views/layouts/partials/_footer.html.haml
%p.muted.credit
  = t('private.footer_html', default: 'footer text', disclaimer: PRIVATE_DATA['legal_disclaimer_link'])

app/views/layouts/partials/_ga.html.haml
- unless Rails.env.test?
  %script{type: 'text/javascript'}
    var _gaq = _gaq || [];
    _gaq.push(['_setAccount', '#{PRIVATE_DATA['ga_tracker']}']);
    _gaq.push(['_setDomainName','#{PRIVATE_DATA['ga_tracker_domain']}']);

    (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
    })();

    if (((_ref = window.history) != null ? _ref.pushState : void 0) && window.history.replaceState && typeof Turbolinks !== 'undefined') {
    document.addEventListener('page:change', function() {
    if (window._gaq != null) {
    _gaq.push(['_trackPageview']);
    } else if (window.pageTracker != null) {
    pageTracker._trackPageview();
    } })
    } else {
    _gaq.push(['_trackPageview']);
    }

-# NOTE:
-# removed JS indentation to keep HAML happy
-# not using :javascript so can have type on script tag for turbolinks

app/views/layouts/partials/_navbar.html.haml
/ Fixed navbar
.navbar.navbar-inverse.navbar-fixed-top
  .container
    .navbar-header
      %button.navbar-toggle{data: {target: '.navbar-collapse', toggle: 'collapse'}, type: 'button'}
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      = link_to branding_text, root_path, class: 'navbar-brand'
    .collapse.navbar-collapse
      %ul.nav.navbar-nav
        %li{class: active_tab('dashboard')}= link_to t('menu.home'), dashboard_path
        - if current_user && current_user.role?('user')
          %li
            %a{href: '#'}= t('menu.messages')
          %li.dropdown
            %a.dropdown-toggle{data: {toggle: 'dropdown'}, href: '#'}
              = t('menu.profile')
              %b.caret
            %ul.dropdown-menu
              %li
                %a{href: '#'}= t('menu.details')
              %li
                %a{href: '#'}= t('menu.licensing')
              %li
                %a{href: '#'}= t('menu.education')
          %li
            %a{href: '#'}= t('menu.reports')
          - if current_user.role?('manager')
            %li{class: active_tab('admin')}= link_to t('menu.admin'), admin_path
        %li{class: active_tab('help')}= link_to t('menu.help'), help_path
      %ul.nav.navbar-nav.navbar-right
        %li
          - if user_signed_in?
            %p.navbar-text.avatar
              = image_tag(avatar_url(current_user), size: '30x30')
              &nbsp;
              = link_to "#{current_user.username}&nbsp;".html_safe, edit_user_registration_path
              = link_to '<span class=\'glyphicon glyphicon-cog\'></span>'.html_safe, edit_user_registration_path
              &nbsp;&nbsp;|&nbsp;
              = link_to t('menu.logout').html_safe, destroy_user_session_path, method: 'delete'
          - else
            - unless controller_name == 'dashboard' && action_name == 'index'
              %p.navbar-text
                &nbsp;
                = link_to t('menu.login').html_safe, new_user_session_path
                &nbsp;|&nbsp;
                = link_to t('menu.register').html_safe, new_user_registration_path