config/routes.rb
Rails.application.routes.draw do

  resources :profiles, only: [:edit, :update, :destroy, :create]

  get '/admin' => 'admin#index'
  get '/dashboard' => 'dashboard#index'
  get '/help' => 'help#index'

  devise_for :users, controllers: {confirmations: 'local_devise/confirmations',
                                   registrations: 'local_devise/registrations',
                                   unlocks: 'local_devise/unlocks',
                                   passwords: 'local_devise/passwords'}

  root 'dashboard#index'

  get 'devise_usage_report', to: 'devise_usage_log#devise_usage_report'
  get 'close_devise_usage_report', to: 'devise_usage_log#close_devise_usage_report'

end

app/models/devise_usage_log.rb
class DeviseUsageLog < ActiveRecord::Base

  classy_enum_attr :action, enum: 'DeviseAction', allow_nil: true

  def self.fetch_usage_report_entries(num_days = 10)
    # rubocop:disable MultilineOperationIndentation
    DeviseUsageLog.where('created_at > ?', DateTime.now - num_days.days)
                  .order('devise_usage_logs.created_at desc')
                  .order('user_id')
    # rubocop:enable all
  end

  def self.log(resource, new_action)
    return unless User.valid_user?(resource) && (Rails.configuration.respond_to? :devise_usage_log_level)
    level = Rails.configuration.devise_usage_log_level
    if level == :all || (level == :login && new_action == DeviseAction::Login)
      resource.log_devise_action(new_action)
    end
  end
end

app/controllers/devise_usage_log_controller.rb
class DeviseUsageLogController < ApplicationController
  skip_authorization_check only: [:close_devise_usage_report]

  before_action :authenticate_user!
  before_action do |chk|
    chk.send(:check_access_level, 'admin')
  end

  def devise_usage_report
    @num_days = 10 # default
    if params[:num_days]
      @num_days = params[:num_days].to_i if params[:num_days].to_i.between?(1, 60)
    end
    @log_entries = DeviseUsageLog.fetch_usage_report_entries(@num_days)
    authorize! :read, @log_entries
    respond_to do |format|
      format.html { redirect_to admin_path }
      format.js
    end
  end

  def close_devise_usage_report
    respond_to do |format|
      format.html { redirect_to admin_path }
      format.js
    end
  end

end

app/views/devise_usage_log/partials/_devise_report_row.html.haml
%tr
  %td.nowrap= entry.created_at.strftime('%H:%M')
  %td= entry.user_ip
  %td= (entry.username.present?) ? entry.username : '(unknown)'
  %td= entry.role
  %td.nowrap= t(entry.action, scope: 'classy_enum.devise_action') if entry.action.present?

app/views/devise_usage_log/partials/_devise_usage_report.html.haml
%h3 Devise Usage Log for Past #{@num_days} Days
.container
  .row
    .col-md-offset-8.col-md-4
      (#{link_to t('label.close_report').downcase, close_devise_usage_report_path, remote: true})
  .row
    .col-md-8
      <table class='table table-hover table-condensed'>
      - prev_date = ''
      - @log_entries.each do |entry|
        - curr_date = entry.created_at.strftime('%m/%d/%Y')
        - if curr_date != prev_date
          - if prev_date != ''
            </tr><tr><td colspan=5><br /><td></tr></tbody>
          %thead
            %tr
              %th= entry.created_at.strftime('%m/%d/%Y')
              %th= t('label.ip')
              %th= t('label.user')
              %th= t('label.role')
              %th= t('label.action')
          <tbody>
          = render 'devise_usage_log/partials/devise_report_row', entry: entry
        - else
          = render 'devise_usage_log/partials/devise_report_row', entry: entry
        - prev_date = curr_date
      </table>

app/views/devise_usage_log/partials/_devise_usage_report_link.html.haml
%p
  - if current_user.role?('admin')
    = link_to 'Devise Usage Log for Past 30 Days', devise_usage_report_path(num_days: 30), remote: true
  - else
    Need 'admin' access to see Devise Usage Log report.